services:
  os:
    container_name: ubuntu
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile
    volumes:
      - ../..:/home
      - ../../var/www/html:/var/www/html
    working_dir: /home
    tty: true
    ports:
      - "8081:8081"
  nginx:
    container_name: my_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../../var/www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "8083:8083"

  website:
    container_name: website
    build:
      context: .
      dockerfile: ./website/Dockerfile
    volumes:
      - ../../var/www:/var/www
    depends_on:
      - os
